### ISSUE TITLE
Implement automated security checks as a GitHub action.

### ISSUE THREAD

**Issue by AlexTheWizardL** [macxred/cashctrl_ledger#49]
## This issue includes the following steps:

1. Find a package that performs security check operations and is used across multiple open-source projects.
2. Implement security checks. 
    - @AlexTheWizardL will research common security check packages and present possible implementation to @lasuk 
3. Create a GitHub action that will perform code checks.
4. Align code base with new rules

<details>
<summary>For security checks in Python projects, several open source projects use specific tools and configurations to ensure their code is secure. Here are some popular tools and how they are used in various open source projects:
</summary>

### 1. **Bandit**
Bandit is a tool designed to find common security issues in Python code.

**Installation**:
```bash
pip install bandit
```

**Usage**:
```bash
bandit -r path/to/your/code
```

**Configuration**:
You can create a `.bandit` configuration file to customize the checks. Here is an example:
```ini
[bandit]
targets: path/to/your/code
skips: B101,B404
```

#### **OpenStack**
- **Linter**: `bandit`
- **Rules**:
  - Uses a `.bandit.yml` configuration file.
  - Example configuration:
    ```yaml
    excludes:
      - "/tests/"
    skips: [B101, B404]
    ```

#### **Django**
- **Linter**: `bandit`
- **Rules**:
  - Uses a `.bandit.yml` configuration file.
  - Example configuration:
    ```yaml
    excludes:
      - "/tests/"
    skips: [B101, B404]
    ```

### 2. **Safety**
Safety checks your installed dependencies for known security vulnerabilities.

**Installation**:
```bash
pip install safety
```

**Usage**:
```bash
safety check
```

**Configuration**:
You can create a requirements file or use your existing one and run safety against it.

#### **Pipenv**
- **Linter**: `safety`
- **Rules**:
  - Uses the default configuration to check the dependencies.

### 3. **Snyk**
Snyk scans for vulnerabilities in dependencies and provides fixes.

**Installation**:
```bash
pip install snyk
```

**Usage**:
```bash
snyk test
```

#### **TensorFlow**
- **Linter**: `snyk`
- **Rules**:
  - Uses the default configuration to check the dependencies.

### How to Integrate Security Checks in Your Project

To integrate these security tools into your project, follow these steps:

1. **Install the tools**:
   ```bash
   pip install bandit safety snyk
   ```

2. **Create configuration files**:
   - `.bandit.yml` for Bandit:
     ```yaml
     excludes:
       - "/tests/"
     skips: [B101, B404]
     ```

   - Ensure your dependencies are listed in a `requirements.txt` or `Pipfile`.

3. **Run the tools**:
   - **Bandit**:
     ```bash
     bandit -r path/to/your/code
     ```
   - **Safety**:
     ```bash
     safety check
     ```
   - **Snyk**:
     ```bash
     snyk test
     ```

4. **Integrate with CI/CD**:
   Add these tools to your CI/CD pipeline to ensure security checks are performed on every build. For example, in a GitHub Actions workflow:
   ```yaml
   name: Security Checks

   on: [push]

   jobs:
     bandit:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install bandit safety snyk
       - name: Run Bandit
         run: bandit -r path/to/your/code
       - name: Run Safety
         run: safety check
       - name: Run Snyk
         run: snyk test
   ```
</details>
 
Security checks should be included for the [cashctrl_api](https://github.com/macxred/cashctrl_api) and [cashctrl_ledger](https://github.com/macxred/cashctrl_ledger) packages
